### ISSUE TITLE
GCP kubevirt-button bucket permissions

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/kubevirt.github.io#121]
While attempting to use the demo for GCP on kubevirt.io I found that the kubvirt-button bucket on Google Cloud Storage isn't accessible and get the error message:
    
> You need the storage.objects.list permission to list objects in this bucket. Ask a project or bucket owner to give you this permission and try again.

**Comment by karmab** [comment]
thanks for reporting @j-griffith this is fixed

**Comment by j-griffith** [comment]
Confirmed, thanks @karmab !
