### ISSUE TITLE
http://kubevirt.io should redirect to https://

### ISSUE THREAD

**Issue by e-minguez** [kubevirt/kubevirt.github.io#123]
Currently kubevirt.io is served both http and https. It would be great if http traffic is redirected to https :)

**Comment by iranzo** [comment]
This is what we do use at <https://citellus.org> :  <https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/>

**Comment by iranzo** [comment]
Who can deal with this?

**Comment by jparrill** [comment]
Done
