### ISSUE TITLE
In AWS+GCP pages, clicking on an external link should create a new tab 

### ISSUE THREAD

**Issue by rwsu** [kubevirt/kubevirt.github.io#128]
A new tab should be created, so the user can come back to the original tab to see the lab instructions after they have started their instance.

**Comment by mindreeper2420** [comment]
@rwsu I can take this one, but cannot assign myself issues. Can you either update my permissions or assign this to me? Thanks!

**Comment by rwsu** [comment]
@scollier Can you assign Adam to this issue? I don't have permissions.
