### ISSUE TITLE
EC2 Push-button Deploy fails due to overlapping routes

### ISSUE THREAD

**Issue by xsgordon** [kubevirt/kubevirt.github.io#138]
Following the push-button deploy instructions for EC2 I found the weave pod going into a crash back-off loop (which in turn prevents coredns and the kubevirt pods from coming up), digging into the logs I saw this:

```
$ kubectl logs weave-net-x588f -c weave -n kube-system
Network 172.30.0.0/16 overlaps with existing route 172.30.0.0/24 on host
```
172.30.0.0/16 is the route associated with my existing VPC, which I can change/replace, but this requirement wasn't mentioned in the instructions.

https://github.com/kubevirt/kubevirt.github.io/blob/master/pages/ec2.md

**Comment by karmab** [comment]
fixed
