### ISSUE TITLE
Origin install instructions are outdated

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt.github.io#156]
/kind bug

There is content which is still copied from the docs manually: https://github.com/kubevirt/kubevirt.github.io/blob/master/pages/get_kubevirt.md. 

It shows the wrong SCC instructions for installing latest kubevirt on an openshift cluster.

This page contains sensible instructions. We should either serve it from the user-guide or ensure that an automated process is in place. People will repeatedly have a bad experience when installing kubevirt.

See for instance https://groups.google.com/d/msgid/kubevirt-dev/CAGg6-xhbrKS1aUqh5zOgAdJst3%2BtPiWeR3u0uwOq9%3D7j05H5Jw%40mail.gmail.com?utm_medium=email&utm_source=footer of the latest visible issue.

**Comment by karmab** [comment]
ack

**Comment by karmab** [comment]
addressed manually in https://github.com/kubevirt/kubevirt.github.io/pull/166 but need to decide what to do with this doc page at all

**Comment by karmab** [comment]
i wonder if it makes sense to simply redirect to 

```
https://kubevirt.io/user-guide/#/installation/README
``` 

@rmohr @fabiand @scollier  ?

**Comment by fabiand** [comment]
Yes - user guide should have it!

It#s a broader topic to revamp user-guide to better fit into the website.
