### ISSUE TITLE
Getting started guide is outdated

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt.github.io#160]
From https://github.com/kubevirt/kubevirt/issues/1316#issuecomment-437414568

> Im following the kubevirt.io demo for using minishift. http://kubevirt.io/get_kubevirt/.
> Host is F29 desktop stock. I've tried VERSION=0.8.0 per the demo, as well as v0.95.0 and v0.10.0
> origin-clients-3.11.0-1.fc29.x86_64
> minishift-1.26.1-linux-amd64

We should fix this.

**Comment by karmab** [comment]
yes, waiting for mark overall feedback to address all of it once

**Comment by karmab** [comment]
@fabiand fixing some CI stuff and we will then update the pages with latest kubevirt release (0.10.0)
