### ISSUE TITLE
workaround for missing vms in kernel of minishift image

### ISSUE THREAD

**Issue by markllama** [kubevirt/kubevirt.github.io#165]
minishift VM does not enable vms in kernel.  

Add this line to the try-me where the other oc setup commands are and the demo will complete as expected:

`kubectl create configmap -n kube-system kubevirt-config --from-literal debug.useEmulation=true`

**Comment by karmab** [comment]
addressed in https://github.com/kubevirt/kubevirt.github.io/pull/166
