### ISSUE TITLE
Clicking on docs link at https://kubevirt.io returns 404 error

### ISSUE THREAD

**Issue by tylerauerbeck** [kubevirt/kubevirt.github.io#176]
When visiting the https://kubevirt.io site and clicking on the docs link at the top right hand of the screen, you are returned a 404 error with the following information: 

```
...snip...

File not found

The site configured at this address does not contain the requested file.
...snip...
```

**Comment by tripledes** [comment]
@tylerauerbeck I'm closing this issue as it seems to be fixed already and I'm doing some housekeeping. Please feel free to open a new one if you it persists. Thanks!
