### ISSUE TITLE
Volume sources links are broken

### ISSUE THREAD

**Issue by nellyc** [kubevirt/kubevirt.github.io#178]
On the docs, when going to this section:
https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#volumes

all the links under it are not taking me to the relevant section
seems like upper/lower case issue
for example
https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#persistentVolumeClaim
vs
https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#persistentvolumeclaim

**Comment by tripledes** [comment]
Hey @nellyc 

Sorry for taking this long to reply. The pages/sections you mentioned belong to the [user-guide](https://github.com/kubevirt/user-guide).
