### ISSUE TITLE
GCP Getting started uses old 0.8.0

### ISSUE THREAD

**Issue by jdonalds** [kubevirt/kubevirt.github.io#184]
Easy install calls out old 0.8.0 image @ http://kubevirt.io/pages/gcp.html

VM install then fails in "Use Kubevirt lab"
kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml

fails since new lan VM.yaml is for newer version.

**Comment by karmab** [comment]
you're right, user should be instructed to create image from latest image (and screenshot should somehow reflect that).
fixed in https://github.com/kubevirt/kubevirt.github.io/pull/186
