### ISSUE TITLE
GCP Getting started uses old 0.8.0

### ISSUE THREAD

**Issue by jdonalds** [kubevirt/kubevirt.github.io#185]
Easy install calls out old 0.8.0 image @ http://kubevirt.io/pages/gcp.html

VM install then fails in "Use Kubevirt lab"
kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml

fails since new lab VM.yaml is for newer version.

**Comment by karmab** [comment]
closing as duplicate of https://github.com/kubevirt/kubevirt.github.io/issues/184
