### ISSUE TITLE
"Get Kubevirt" page should have an index/be ordered

### ISSUE THREAD

**Issue by e-minguez** [kubevirt/kubevirt.github.io#203]
As a user, if you start reading the get_kubevirt site and copy & paste instructions, it is confusing to find 'KubeVirt on an existing Kubernetes cluster' after 'KubeVirt Quickstart'. Is the operator not enough?

**Comment by karmab** [comment]
it is, we re planning to remove the KubeVirt on an existing Kubernetes cluster section all together

**Comment by karmab** [comment]
To be addressed by https://github.com/kubevirt/kubevirt.github.io/pull/202

**Comment by tripledes** [comment]
@e-minguez how does it look now? Do you think the index is still needed?

**Comment by e-minguez** [comment]
It is ok, but I would say to have a single 'TRY IT' then have sections for different platforms such as:

- minikube/minishift
- plain vanilla k8s
- okd/ocp
- aws
- gcp

**Comment by tripledes** [comment]
@e-minguez thanks for the suggestions, we'll be reorganizing the contents where needed to ease the process of getting started with KubeVirt, specially for new users.

/close
