### ISSUE TITLE
Not able to spin up a container for hosting a local website

### ISSUE THREAD

**Issue by DirectedSoul1** [kubevirt/kubevirt.github.io#213]
While trying to spin up the container using the 
`sudo docker run -d --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll jekyll serve --watch` command on RHEL 7 

**OS Version**
```
[root@localhost kubevirt.github.io]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
Im getting the error: 
```
.
.
.
Fetching jekyll-paginate 1.1.0
Installing jekyll-paginate 1.1.0
Fetching jekyll-redirect-from 0.15.0
Installing jekyll-redirect-from 0.15.0
There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
likely that you need to grant write permissions for that path.
```
**Docker output**
```
[root@localhost kubevirt.github.io]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
596e322e7886        jekyll/jekyll       "/usr/jekyll/bin/ent…"   6 minutes ago       Exited (23) 4 minutes ago                       kubevirtio
```

**Comment by jparrill** [comment]
Is this still applying? It works for me: https://pastebin.com/NfA61ZQb

**Comment by iranzo** [comment]
I've also tested it with:

~~~sh
sudo chcon -Rt svirt_sandbox_file_t .
sudo docker run -d --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll jekyll serve --watch
~~~

And works for me

**Comment by DirectedSoul1** [comment]
It works for me on my Fedora 29 , and on* Centos* and *RHEL* this will not
work.

Shashank *Hegde*

Systems Engineer, RHCE

Red Hat MA <https://www.redhat.com/>

314 Littleton Rd

shegde@redhat.com
M: 6179925192
<https://red.ht/sig>

**Comment by iranzo** [comment]
Container is not provided by us, just as a way to make it easier to debug the website changes, I agree it makes it more convenient that having to install jekyll locally, but not really sure if it's something that we should be handling or not as it's outside of our hands

**Comment by tripledes** [comment]
@DirectedSoul1 I've been testing this myself on a CentOS7 VM, here my findings:

* I hit the issue as soon as I started the container
* Tried different SELinux contexts with different levels of (un)success
* Realized one difference between my Fedora host and my CentOS VM:

      $ ls -ld /home/sjr # Fedora 30
      drwx--x--x. 47 sjr sjr 4096 Jun 12 12:22 /home/sjr

While on CentOS, and I presume in RHEL would be the same but you'll tell us, my user's home is set to 700 (drwx------), which no matter what SELinux context I used, it always denied write access for the container to the shared volume.

I tried setting my user's home directory to *0711*, then applied the steps as listed on our README and it worked properly. Could you please verify?

    $ chmod 711 $HOME
    $ git clone https://github.com/kubevirt/kubevirt.github.io
    $ cd kubevirt.github.io
    $ sudo chcon -Rt svirt_sandbox_file_t .
    $ sudo docker run --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll jekyll serve --watch

Thanks!

**Comment by karmab** [comment]
since the issue can be handled either by disabling selinux in the container or by labelling,closing this

**Comment by codificat** [comment]
You can't disable SElinux inside the container, and I wouldn't recommend disabling it on the host.

About labeling: that's precisely the issue here, right? The README contains instructions from labeling that, if I understand correctly from the conversation, don't work well on some systems...

So, this isn't really resolved, right?  It sounds to me that there are changes needed in the README, and that #213 is a proposal for these... no?

**Comment by iranzo** [comment]
This change in README instructs user to use container relabelling of filesystem so if it's executed outside of the website folder, for example on / by accident, it will relabel the full filesystem.

A note should be put before the command, but never, default to make changes on the user system that could result in a bigger issue.

**Comment by tripledes** [comment]
> This change in README instructs user to use container relabelling of filesystem so if it's executed outside of the website folder, for example on / by accident, it will relabel the full filesystem.
> 

That isn't accurate. 


https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

> A note should be put before the command, but never, default to make changes on the user system that could result in a bigger issue.

**Comment by codificat** [comment]
It seems that these comments actually belong to #246 - sorry I misquoted the reference to the PR earlier

**Comment by DirectedSoul1** [comment]
I just tested this on my RHEL 7.5
```
cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.5 (Maipo)
```
And from my local browser, was able to access the website http://0.0.0.0:4000
![Screenshot from 2019-06-13 16-43-33](https://user-images.githubusercontent.com/41084673/59466162-9a34c200-8dfa-11e9-912b-1b65777e0802.png)
