### ISSUE TITLE
Ruby Sass EOL

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#224]
From CI logs... seems that something should be updated:

Ruby Sass has reached end-of-life and should no longer be used.
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
Successfully installed sass-3.7.4

**Comment by iranzo** [comment]
For example: https://travis-ci.org/kubevirt/kubevirt.github.io/builds/548026991#L543

**Comment by iranzo** [comment]
Related: https://github.com/jekyll/jekyll-sass-converter/issues/74

**Comment by iranzo** [comment]
From that one, the libraries are waiting for Jekyll 4.0 to arrive and get dependant libraries moved to stable and new dependency chime in.

As we don't directly depend on it, it should be 'safe' to close this bug: https://github.com/jekyll/jekyll-sass-converter/issues/74#issuecomment-516217160

**Comment by iranzo** [comment]
@ptrnull ^ above, can we close it?

**Comment by ptrnull** [comment]
@iranzo all right
/close
