### ISSUE TITLE
OpenShift lab might be out of date

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt.github.io#254]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There is an OpenShift lab (labeled "OCP lab") in https://kubevirt.io/labs/ocp that seems to be out of date

**What you expected to happen**:

The lab should be updated or removed as appropriate

**Anything else we need to know?**:

The lab appears to have been originally based on the [kubevirt-tutorial](https://github.com/kubevirt/kubevirt-tutorial). That tutorial has evolved, is now based on Kubernetes - maybe it's worth doing a joint review.

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by iranzo** [comment]
Missing images in the labs seem to come from: 

https://github.com/sabre1041/managing-ocp-install-beyond/pull/200/files
