### ISSUE TITLE
New blog posts are hidding inside 'blog' section giving no visibility

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#263]
For the casual visitor, new blog posts are not featured in the website, a sidebar on the front page containing latest posts could be a good addition.

**Comment by iranzo** [comment]
https://marvelapp.com/527b7h7 as an example

**Comment by iranzo** [comment]
@mindreeper2420 I thought that you were involved here, can you help on this similar to metal3.io website?

**Comment by codificat** [comment]
/reopen
we're going to review long standing site design issues
