### ISSUE TITLE
Articles should contain tags to relate with others and allow browsing by tags

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#269]
Website has many articles that could benefit from using tags to inter-relate them for additional discovery options

**Comment by iranzo** [comment]
Related with #268

**Comment by iranzo** [comment]
@mindreeper2420 I thought that you were involved here, can you help on this similar to metal3.io website?

**Comment by mindreeper2420** [comment]
@iranzo I'm not entirely sure the ask here - I'm not active on this project right now, as I was just brought in the help build the site and set it up for future updates. Regarding the metal3.io site, I'd have to talk with the UX team on it currently to figure out what is going on.

**Comment by iranzo** [comment]
Hi, for metal3 we're ok, but your name came out as you were working on this and wanted to get advice on how to move forward with some design changes inspired with current experience acquired.

Would you appoint someone who could take care of this?

**Comment by iranzo** [comment]
Merged tags in source branch
