### ISSUE TITLE
Add a FAQ to website

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#298]
It's probably worth improving the quickstart in the website, and a FAQ might be a nice addition too, but let's handle that in the website repo.

But regardless of that, I still think it's 6 words is a bit too short for an explanation of what we're doing here.

_Originally posted by @codificat in https://github.com/kubevirt/katacoda-scenarios/pull/2_

**Comment by iranzo** [comment]
FAQ in #299

**Comment by ptrnull** [comment]
@iranzo as spoken, rename the title to "Add a FAQ to the website #298"

**Comment by mazzystr** [comment]
@codificat  In light of CNCF technical documentation meeting and the FAQ topic I would like to  close this issue.

**Comment by codificat** [comment]
> @codificat In light of CNCF technical documentation meeting and the FAQ topic I would like to close this issue.

Ok.

Can you please elaborate a bit more on the reasoning provided by tech writer experts? So we document the decision a bit more.

After that, feel free to review and approve #650, which will close this issue.

**Comment by mazzystr** [comment]
Sure!

* re faqs ... In their experience faqs need continuous maintenance.  Content should be constantly cycled back into official documentation.  FAQ's easily becomes a dense forest and difficult to navigate....and unused
