### ISSUE TITLE
Issue on Minikube Try it button

### ISSUE THREAD

**Issue by jparrill** [kubevirt/kubevirt.github.io#300]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

When the Tutorial says to execute this command to extract Kubevirt latest version:

```
# On Linux you can obtain it using 'curl' via:
export KUBEVIRT_VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases|grep tag_name|sort -V | tail -1 | awk -F':' '{print $2}' | sed 's/,//' | xargs)
```

The version extracted is not correct

**What you expected to happen**:

(Now) the laetst version is `v0.19.0` but the command extracts `v0.19.0-rc.0`

```
λ kvio-lab-images git:(feature/add_doc) export KUBEVIRT_VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases|grep tag_name|sort -V | tail -1 | awk -F':' '{print $2}' | sed 's/,//' | xargs)

Σ kvio-lab-images git:(feature/add_doc) echo ${KUBEVIRT_VERSION} 
v0.19.0-rc.0
```

**Anything else we need to know?**:

We need to avoid `rc`, `alpha`, `beta`, etc... versions from the tutorial.

**Comment by ptrnull** [comment]
What about cutting it?
curl -s https://api.github.com/repos/kubevirt/kubevirt/releases|grep tag_name|sort -V | tail -1 | awk -F':' '{print $2}' | sed 's/,//' | xargs | cut -d'-' -f1

it works even if there is no "-blabla".

**Comment by jparrill** [comment]
should be enough ;)

**Comment by iranzo** [comment]
Are you submitting the PR?
