### ISSUE TITLE
Use Krew on Kubernetes Labs from Lab1 on Kubevirt.io

### ISSUE THREAD

**Issue by jparrill** [kubevirt/kubevirt.github.io#301]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

It should be good to change using `virtctl` by `kubectl virt` using [**krew**](https://github.com/kubernetes-sigs/krew) plugin management on [Lab1 Page](https://kubevirt.io/labs/kubernetes/lab1).

This one concretelly:

---
- To start a Virtual Machine you can use:
```
./virtctl start testvm
```
---

To do this we should to change the Image provision method and pre-install krew, then change the tutorial to use `kubectl krew install virt` and then manage VMs with `kubectl virt ...`

**Comment by jparrill** [comment]
Sorry, reusing the issue :D

**Comment by ptrnull** [comment]
Commented in https://groups.google.com/d/msg/kubevirt-dev/3xo4KOL1hgI/HavB5iCYBQAJ

**Comment by jparrill** [comment]
Let's wait for [this issue](https://github.com/kubevirt/kubevirt/issues/2410) to be solved and then we could change the labs. But we also we need to maintain the backward compatibility, just put the `krew` command on the lab and also the alternative with `virtctl` one. Preparing the WIP PR

**Comment by jparrill** [comment]
reviewed, solved. Closing
