### ISSUE TITLE
Outdated AMIs on Try it! Button for AWS webpage

### ISSUE THREAD

**Issue by jparrill** [kubevirt/kubevirt.github.io#305]
**Is this a BUG REPORT or FEATURE REQUEST?**:
kind bug

**What happened**:

When you access to **Try it on AWS** button of kubevirt.io page, the AMIs exposed on the guide are outdated: 

- https://kubevirt.io/pages/ec2

**What you expected to happen**:

When a new image creation build it's triggered a new PR needs to be created agains the Kubevirt.github.io repo in order to update those AMIs, or maybe look for another more easy solution like expose the Json file generated ([from here](https://jenkins-kubevirt.apps.ci.centos.org/job/dev/job/jodavis/job/kvio-lab-images/lastSuccessfulBuild/artifact/new-images.json))

**Comment by iranzo** [comment]
Closing as duplicate from #365
