### ISSUE TITLE
Separate css styles from html tags

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#333]
![image](https://user-images.githubusercontent.com/312463/64589137-a81bc400-d3a4-11e9-85e1-abeed9632764.png)
https://www.dareboost.com/en/report/d_15d77414a90b99843ddb4b7a1?reportIds=d_15d77414a90b99843ddb4b7a1

**Comment by codificat** [comment]
/reopen
we're going to review long standing site design issues
