### ISSUE TITLE
Missing images on KubeVirt Network deep dive blog post

### ISSUE THREAD

**Issue by brysk** [kubevirt/kubevirt.github.io#343]
Hi,

There is a problem with images on KubeVirt Network Deep Dive: https://kubevirt.io/2018/KubeVirt-Network-Deep-Dive.html it worked couple fo days ago 

![image](https://user-images.githubusercontent.com/455368/65751185-441a2f00-e10a-11e9-9c68-bc55a6b55314.png)

Can you please fix it, thanks!

**Comment by slintes** [comment]
@codificat can someone have a look please? Thanks!

**Comment by iranzo** [comment]
I'll check it!

**Comment by iranzo** [comment]
Handled in https://github.com/kubevirt/kubevirt.github.io/pull/344

**Comment by iranzo** [comment]
@brysk can you confirm that https://5d8dc73e4c1ed40008f70a90--kubevirtio.netlify.com/2018/kubevirt-network-deep-dive shows as it was previously?

**Comment by iranzo** [comment]
Also, this PR fixes: https://deploy-preview-344--kubevirtio.netlify.com/2018/kubevirt-network-rehash

**Comment by brysk** [comment]
@iranzo still doesn't work, I have emptied cache and reloaded website.

For example this png file cannot be fetched:
https://www.kubevirt.io//assets/images/diagram.png

**Comment by codificat** [comment]
It seems that a DNS issue caused this, see #346.

**Comment by iranzo** [comment]
#347 should fix it in the meantime but also #344 will make the articles look similar to the way it's done in others

**Comment by iranzo** [comment]
@brysk no, it will depend on the PR being merged, I want confirmation that the following URL's:

- https://5d8dc73e4c1ed40008f70a90--kubevirtio.netlify.com/2018/kubevirt-network-deep-dive
- https://deploy-preview-344--kubevirtio.netlify.com/2018/kubevirt-network-rehash

Do look nice on your side so that we can merge the PR and have the original url fixed

**Comment by iranzo** [comment]
With the merge of #347 the images now load on the original URL reported

**Comment by brysk** [comment]
@iranzo oh right, I misunderstood - looks good yes

**Comment by iranzo** [comment]
@brysk PR have been merged (347) and (344) is on its way, are you ok if we close this issue?

Thanks!
Pablo

**Comment by iranzo** [comment]
Closing as per previous confirmation
