### ISSUE TITLE
Enhance linkchecker so that url_swap can be overriden by periodic jobs

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#345]
Check #343 for example of a broken image link that passed so far the procedure

/kind bug

**Comment by iranzo** [comment]
I was thinking a bit about this, linkchecker does internally replace 'external links' to 'www.kubevirt.io' to local links to "/" so it would never catch issues with the configured DNS domain name.

- We need that setting to remain in place, so that future-dated posts can be validated and given the verify tick on checks (as the external link will always fail until the post is published)

- We'll need to add a new job to check all the links but with a different configuration file that doesn't do this renaming and only on branch master, so that the 'current' website is tested also using external links, hence detecting issues with domain

**Comment by iranzo** [comment]
After some checks, in order to fix we need to edit Rakefile included in this repo to allow external modification of the `urlswap` parameter for html-proofer so that the prow job that runs this check clears the default setting so that external links are checked when the 'server' is the website itself

**Comment by jparrill** [comment]
I will go through that between tomorrow and next week.
