### ISSUE TITLE
lab2 on minkube not working: 2 default storageclasses were found

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt.github.io#350]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

While attempting [lab 2](https://kubevirt.io/labs/kubernetes/lab2) on minikube, the creation of the `fedora` PVC (`pvc_fedora.yml`) fails:

```
$ kubectl create -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/pvc_fedora.yml
Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/pvc_fedora.yml": persistentvolumeclaims "fedora" is forbidden: Internal error occurred: 2 default StorageClasses were found
$ kubectl get storageclass
NAME                 PROVISIONER                AGE
hostpath (default)   hostpath                   115s
standard (default)   k8s.io/minikube-hostpath   62m
```

**What you expected to happen**:

Lab instructions should work and not cause errors.

**Anything else we need to know?**:

> URL where the problem can be found ... 

https://kubevirt.io/labs/kubernetes/lab2

> If the issue is with a lab, please provide information about your environment, platform, versions, ...

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

$ virtctl version
Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by codificat** [comment]
As seen in the description, there's a pre-existing `StorageClass` already configured to use a hostpath provisioner.

Deleting the resources created by `storage-setup.yml` allows the PVC creation to succeed.

Then the import fails... but that's another story.

**Comment by codificat** [comment]
> Then the import fails... but that's another story.

Created #351 for that

**Comment by alosadagrande** [comment]
I'll take a look. Seems there is already a hostpath storageclass defined in minikube by default, which is called standard and it's kind of hostpath. Probably there is no need, at least in minikube, to create the storageclass in storage-setup.yml or if needed it can't be configured as default sc in yaml:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" <--
provisioner: hostpath
```

**Comment by iranzo** [comment]
Hi @alosadagrande, thing is that code in labs should be generic for all environments (GCP, AWS, Katacoda, minikube, etc), would it be possible to use something different so that the same set of yamls can be used on all environments?

**Comment by alosadagrande** [comment]
I can assert that minikube v1.4.0 comes with a default storage class:

```
$ kubectl get sc
NAME                 PROVISIONER                AGE
standard (default)   k8s.io/minikube-hostpath   27m
```

**Comment by iranzo** [comment]
> I can assert that minikube v1.4.0 comes with a default storage class:
> 
> ```
> $ kubectl get sc
> NAME                 PROVISIONER                AGE
> standard (default)   k8s.io/minikube-hostpath   27m
> ```

We might add a step on the minikube tutorial for setting up that removes it to avoid further conflicts?

**Comment by alosadagrande** [comment]
I would recommend to select the storageClass when requesting the pvc as shown below: 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath
```
Also related to issue #351 I also suggest to reduce the size of the PVC to 4GB (minimum size required to run Fedora30 as vmi) since minikube is using tmpfs as rootfs. 

In my tests, the PVC size is related to the amount of memory needed in the virtual machine running k8s. So, if we request 10Gi, the vm needs to be run with 12Gi at least. Note that this is only applicable to minikube.
