### ISSUE TITLE
Can't get minikube + kubevirt working

### ISSUE THREAD

**Issue by amontalban** [kubevirt/kubevirt.github.io#353]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I'm following this guide https://kubevirt.io/quickstart_minikube/ and can't get `virt-handler` pod to start.

```
Andres-MBP2019:~ andres$ kubectl get pods -n kubevirt
NAME                              READY   STATUS              RESTARTS   AGE
virt-api-84d977f4b8-fncqb         1/1     Running             0          74m
virt-api-84d977f4b8-xj2cd         1/1     Running             0          74m
virt-controller-58f479f68-5cjgr   1/1     Running             0          73m
virt-controller-58f479f68-nrzpf   1/1     Running             0          73m
virt-handler-rhw7v                0/1     RunContainerError   0          73m
virt-operator-fddd98fc8-vjnk5     1/1     Running             0          79m
virt-operator-fddd98fc8-zkll9     1/1     Running             0          79m
```

Output of `kubectl describe pod virt-handler-rhw7v -n kubevirt`: https://gist.github.com/amontalban/f14d65880bd3e2bccdf5179ab85e4e86

**What you expected to happen**:
To have a fully working kubevirt deployment.

**How to reproduce it (as minimally and precisely as possible)**:

Follow https://kubevirt.io/quickstart_minikube/ guide on a macOS 10.14.6 with VirtualBox 6.0.10.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Not yet installed
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release):
```
NAME=Fedora
VERSION="30 (Container Image)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
```
- Kernel (e.g. `uname -a`): 
```Linux minikube 4.15.0 kubevirt/kubevirt#1 SMP Fri Aug 2 16:17:56 PDT 2019 x86_64 GNU/Linux```
- Install tools:
- Others:

**Comment by iranzo** [comment]
Hi, We've a related bug being handled in #352 can you try the file referenced there? (hasn't yet been commited to the repo)

In short, as minikube now has a storage class included, it crashes when creating the vm, so we changed the pvc_fedora to use a different one.

@alosadagrande did you face this issue during your PR testing?

**Comment by iranzo** [comment]
Fedora 30 host:
![image](https://user-images.githubusercontent.com/312463/66383994-38f2b900-e9be-11e9-8da3-7d1f6abb5966.png)

Minikube version:
![image](https://user-images.githubusercontent.com/312463/66384120-71929280-e9be-11e9-8db1-3752242c2ef6.png)


Deployed using 0.21.0 operator

So, as you mentioned, the prior error was related to minikube version.


Following on your comment at https://github.com/kubevirt/kubevirt.github.io/issues/353#issuecomment-535681283

Check the 'alternate' PVC at: https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/c4b1a07867a62bb5d05bfc3fb4d513220153ba6d/labs/manifests/pvc_fedora.yml


However, at current status, VM importer process seems to fail (tested on katacoda and minikube) and we're working on it as part of the PR #352 mentioned before

**Comment by alosadagrande** [comment]
This is a minikube specific issue. Using the "alternate" PVC you mentioned I was able to import the cloud image from Fedora.

See commit diff at https://github.com/kubevirt/kubevirt.github.io/pull/352/commits/c4b1a07867a62bb5d05bfc3fb4d513220153ba6d

**Comment by alosadagrande** [comment]
Several PRs have been merged which resolves the issue with duplicated storageClasses. 

Also, more information to Minikube users when executing lab2 has been provided.

Waiting for feedback.

**Comment by iranzo** [comment]
Closing because of merged changes in repo, please reopen or add comments in case it's not
