### ISSUE TITLE
Clarify on LAB2 the minikube specifics

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#361]
**Is this a BUG REPORT or FEATURE REQUEST?**:

LAB2 has a section for minikube specifics for accesing the VM IP but it is not clearly separated from regular lab.

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by codificat** [comment]
Ideally we should aim at not having "minikube specifics" to begin with, so we wouldn't need to maintain differences

**Comment by alosadagrande** [comment]
PR was merged. Issue can be closed
