### ISSUE TITLE
LAB2 instructs to ssh to fedoraVM but this might not be reachable

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#362]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Lab informs to ssh to fedora VM IP, but this might not work in real environments as the vm will be in another network unless conecting within the claster.

A nodeport might be required as explained with the minikube specific part

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by alosadagrande** [comment]
PR was merged, issue can be closed
