### ISSUE TITLE
Update KubeVirt  to latest version in already provided AMI

### ISSUE THREAD

**Issue by alosadagrande** [kubevirt/kubevirt.github.io#365]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
I deployed AMI suggested in EC2 and realize that version running KubeVirt is an old version (0.16.1)

**What you expected to happen**:
Deploy KubeVirt latest stable version along with K8S

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...
Issue is at least with AWS AMI images.

**Comment by alosadagrande** [comment]
Found some newer AMIs with newer Kubevirt versions already created. However they are not referenced in the [ec2 lab webpage](https://kubevirt.io/pages/ec2.html) 

Newest KubeVirt's AMI I found is 0.20.7. Latest KubeVirt version at the time of writing is 0.22

**Comment by iranzo** [comment]
Latest images are available at https://jenkins-kubevirt.apps.ci.centos.org/job/cloud-image-builder/job/master/lastSuccessfulBuild/artifact/new-images.json

We should automate the update of the relevant article pointing to that file for checking latest versions or directly providing a link to it

**Comment by iranzo** [comment]
Once we move to travis to generate the website we can automate downloading of json and use https://jekyllrb.com/docs/datafiles/ to automate the ec2lab page automatically with latest amis
