### ISSUE TITLE
No icon/picture shows when using a link of a blogpost in Twitter/LinkedIn

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#372]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When including a URL in a tweet, no picture/icon appears and shows the default one, example: https://twitter.com/ptrnull/status/1184413103393509378
**What you expected to happen**:
To have at least a KubeVirt icon appearing in the miniature icon that references the blogpost/link to the kubevirt.io webpage.

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...
https://twitter.com/ptrnull/status/1184413103393509378

**Comment by ptrnull** [comment]
How to check it:
https://cards-dev.twitter.com/validator

check the following metas:
```
<meta property="og:title" content="Example Page">
<meta property="og:image" content="https://example.com/images/image.jpg">
<meta property="og:description" content="This is just an example page.">
<meta property="og:url" content="https://example.com/page.html">
<meta name="twitter:card" content="summary_large_image">
```

**Comment by ptrnull** [comment]
Official doc from twitter: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

**Comment by ptrnull** [comment]
I doesn't work in LinkedIn neither.
How to check it: https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fkubevirt.io%2F2019%2FKubeVirt_k8s_crio_from_scratch.html

**Comment by iranzo** [comment]
Before:
![imagen](https://user-images.githubusercontent.com/312463/72065483-9b6d9500-32de-11ea-8f14-01641c213dbf.png)

After: (using preview PR: https://deploy-preview-429--kubevirtio.netlify.com/2019/kubevirt_k8s_crio_from_scratch)

![imagen](https://user-images.githubusercontent.com/312463/72066777-b8f02e00-32e1-11ea-995b-63504bdc40d8.png)

**Comment by iranzo** [comment]
Also for Twitter:

![imagen](https://user-images.githubusercontent.com/312463/72066887-010f5080-32e2-11ea-91a9-513566ee5450.png)


/close
