### ISSUE TITLE
[labs] latest gcp image does not have virtctl binary

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt.github.io#374]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Following [lab1](https://kubevirt.io/labs/kubernetes/lab1) on a GCP instance created from the [kubevirt-0.20.7-4](https://storage.cloud.google.com/kubevirt-button/kubevirt-0.20.7-4.tar.gz) image, the step about starting the first VM fails because there's no virtctl binary:

```
$ pwd
/home/centos
$ ls -l virtctl
ls: cannot access virtctl: No such file or directory
```

**What you expected to happen**:

Lab should work as described

**Anything else we need to know?**:

**Comment by iranzo** [comment]
The images we're testing as part of the lab validation now have virtctl correctly installed (lab1 validation succeeds) and we're working with the timeouts for lab validation part2 (but binaries, etc are all there), closing.
