### ISSUE TITLE
html Blockquotes are not differentiate from the rest of the content

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#380]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**: When there is a markdown note indicated with '>' an html blockquote is generated, the css class doesn't distinguish that blockquote from the rest of the text, should be shadowed or boxed to see that there is a blockquote.

**What you expected to happen**: Get the text into the blockquote differentiate from the rest of the text.

**Anything else we need to know?**:

URL where the problem can be found: https://5daec8f20378a30008ccd782--kubevirtio.netlify.com/2019/kubevirt_k8s_crio_from_scratch_installing_kubevirt

**Comment by iranzo** [comment]
Also affects https://github.com/kubevirt/kubevirt.github.io/pull/424

**Comment by mazzystr** [comment]
@ptrnull  Are you referring to how a code block appears to be broken up when there's multiple lines?

Ref: [Procedure / Tasks to performed on source host / Step 3](https://kubevirt.io/2020/win_workload_in_k8s.html)

**Comment by codificat** [comment]
/remove-lifecycle rotten
triaging
