### ISSUE TITLE
Some of the testing scripts for the minikube quickstart don't exist

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#451]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: some of the testing scripts for the minikube quickstart don't exist, check it, add them or correct it.
https://github.com/kubevirt/kubevirt.github.io/tree/source/_includes/scriptlets/quickstart_minikube
Check them in the test_spect:
https://github.com/kubevirt/kubevirt.github.io/blob/source/_includes/scriptlets/quickstart_minikube/test_spec.yaml

**What you expected to happen**:
To be a correlation between the scripts in https://github.com/kubevirt/kubevirt.github.io/blob/source/_includes/scriptlets/quickstart_minikube/ and the test_spect.yml in https://github.com/kubevirt/kubevirt.github.io/blob/source/_includes/scriptlets/quickstart_minikube/test_spec.yaml

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by mazzystr** [comment]
I don't think we have this test harness anymore.  I'm closing.  

If you feel this issue was mistakenly closed please reopen and update the bug description.

Thanks
