### ISSUE TITLE
The search form returns some results from the /build directory

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#466]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: The search form returns some results from the /build directory, css files and tests, that should not happen.

**What you expected to happen**: The results page should contain only results from the content blogposts or any other section available in the KubeVirt web.

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by iranzo** [comment]
Also happens with css and yamls in tests, thanks for the report!
