### ISSUE TITLE
Update community page with badges

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#502]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
Currently community page lists twice fork and star for the repo, would be good to replace it with something more meaningful like the standard 'badges' instead of the button:

https://img.shields.io/github/forks/kubevirt/kubevirt.svg
https://img.shields.io/github/stars/kubevirt/kubevirt.svg

**What you expected to happen**:

- Replace buttons with badges
- Remove 'talk to us section' with relevant icons in the upper part of community leaving more room for the twitter feed

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by codificat** [comment]
/reopen
we're going to review long standing site design issues
