### ISSUE TITLE
404 error - broken link on the "community" page

### ISSUE THREAD

**Issue by scollier** [kubevirt/kubevirt.github.io#51]
http://kubevirt.io/community/docs/

**Comment by scollier** [comment]
http://kubevirt.io/community/docs/getting-started.md

**Comment by scollier** [comment]
http://kubevirt.io/community/docs/getting-started.md#testing

**Comment by scollier** [comment]
http://kubevirt.io/community/docs/

All the /docs links are broken.

**Comment by fabiand** [comment]
Should be fixed now
