### ISSUE TITLE
The blogpost categories doesn't represent the reality

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#510]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**: The blogpost have the category news when they are an article about how to do something or a release, the categories should be a wide list of options.

**What you expected to happen**: to have a well defined list of categories to choose when written a blogpost.

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by iranzo** [comment]
Metal3 uses 'categories' as tags, we might do something similar or keep categories for big buckets and then tags as we're doing in articles
