### ISSUE TITLE
Add the new kubevirt video in the videos section

### ISSUE THREAD

**Issue by ptrnull** [kubevirt/kubevirt.github.io#527]
/kind enhancement

**What happened**: add the new kubevirt video https://www.youtube.com/watch?v=uusM5SyK-vc&feature=youtu.be in the videos section: https://kubevirt.io/videos/

**What you expected to happen**: to find the new video in the /videos/ section of the kubevirt.io webpage

**Anything else we need to know?**:

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by codificat** [comment]
What about getting rid of the videos section and just point to the youtube channel?
