### ISSUE TITLE
HTML Proofer, check only files on PR

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#537]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

When a PR is made, only check the links that were included in the PR for new broken links

Sometimes we get broken links of older relocated files that are not part of this pr to be fixed

**What you expected to happen**:

**Anything else we need to know?**:

https://github.com/gjtorikian/html-proofer#ignoring-new-files (but reverse case, we want to ignore the existing ones)

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by mazzystr** [comment]
@codificat  The regex map described here (https://github.com/gjtorikian/html-proofer#ignoring-new-files) doesn't work as advertised.
* Notice the README uses option url_ignore.  That should be file_ignore
* Notice file_ignore accepts a value of map ( [] ).  The diffable_files map gets processed but the code errors out at the first file with errors found.  I filed a bug here ([issues/588](https://github.com/gjtorikian/html-proofer/issues/588))
