### ISSUE TITLE
Spacer after/before code blocks

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#540]
Code blocks are pretty close to paragraphs, this needs more tuning

Ref: [KNIECO-2271](https://issues.redhat.com/browse/KNIECO-2271)

**Comment by mazzystr** [comment]
This is funny.  I made a big effort to remove the space before/after code blocks.

See result [here](https://kubevirt.io/2020/win_workload_in_k8s.html)

**Comment by mazzystr** [comment]
In organized lists / bullet pointed lists code blocks have large gap above block and no gap below block.  The next element in list has two lines.  See attached screenshot.

It reqs a <br> to get proper spacing but that's ugly
<img width="573" alt="Screen Shot 2020-07-23 at 2 51 54 PM" src="https://user-images.githubusercontent.com/2479463/88343974-79c28100-ccf7-11ea-9394-a8d24ea5504b.png">
