### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by uhlhosting** [kubevirt/kubevirt.github.io#553]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: Followed docs to deploy kubevirt, in the end in dashboard i noticed that 1 service is failing.

**What you expected to happen**: Have kubevirt functional

**Anything else we need to know?**:

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...
```
 {"component":"virt-handler","hostname":"uhl-v1-core-v1180-ztqhocimkzjd-node-2","level":"info","pos":"virt-handler.go:187","timestamp":"2020-04-07T18:43:35.624815Z"}
{"component":"virt-handler","level":"info","msg":"Starting collector: node name=uhl-v1-core-v1180-ztqhocimkzjd-node-2","pos":"prometheus.go:395","timestamp":"2020-04-07T18:43:36.438330Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:36.438425Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer configMapInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:36.438456Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:36.438474Z"}
panic: failed to list labels: out: "", error: could not find binary semanage
goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000426200)
	cmd/virt-handler/virt-handler.go:320 +0x1f3e
main.main()
	cmd/virt-handler/virt-handler.go:476 +0x6e 

 {"component":"virt-handler","hostname":"uhl-v1-core-v1180-ztqhocimkzjd-node-1","level":"info","pos":"virt-handler.go:187","timestamp":"2020-04-07T18:43:28.884801Z"}
{"component":"virt-handler","level":"info","msg":"Starting collector: node name=uhl-v1-core-v1180-ztqhocimkzjd-node-1","pos":"prometheus.go:395","timestamp":"2020-04-07T18:43:30.106519Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:30.117363Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer configMapInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:30.117581Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:223","timestamp":"2020-04-07T18:43:30.117612Z"}
panic: failed to list labels: out: "", error: could not find binary semanage
goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000130500)
	cmd/virt-handler/virt-handler.go:320 +0x1f3e
main.main()
	cmd/virt-handler/virt-handler.go:476 +0x6e 
```

**Comment by alosadagrande** [comment]
What distribution of Kubernetes are you running KubeVirt?

**Comment by uhlhosting** [comment]
@alosadagrande using v1.18.0 .

**Comment by alosadagrande** [comment]
Kubernetes vanilla?

**Comment by uhlhosting** [comment]
1.19.0 would be vanilla :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alosadagrande** [comment]
The community has arrived on the colloquial term “vanilla Kubernetes” to describe an installation of the only the upstream components as released by the Kubernetes project. “Vanilla Kubernetes” 

Why are you saying 1.19?

**Comment by uhlhosting** [comment]
I got it wrong, well this is a vanilla deployment in that case. I was thinking you reffered to as unstable 💣 . It is deployed in openstack under magnum. With coreos image. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alosadagrande** [comment]
Opened a similar issue, in my case I was running Fedora CoreOS:

https://github.com/kubevirt/kubevirt/issues/3129

Summing up:

Set SElinux to permissive. IMHO it is a no-go
Install the **policy-coreutils** package and reboot the node. However, AFAIK this can lead to problems during OKD updates since it manages the OS life-cycle as well, so it can upgrade the OS and face the semanage issue again since it does not come out of the box.

**Comment by uhlhosting** [comment]
I too use CoreOS underlaying for K8S. Will try on Atomic

**Comment by uhlhosting** [comment]
Just noticed i opened the bug in wrong repository . tried today a fresh deployment will fail same semanage missing.

**Comment by alosadagrande** [comment]
You will need to install the proper package that contains semanage on your nodes and reboot them. This is the workaround while fixing this by using a go library instead of semanage.

**Comment by uhlhosting** [comment]
I use latest fedora-coreos images will check about this.

**Comment by uhlhosting** [comment]
rpm-ostree install policycoreutils-python-utils --reboot testing it now.

**Comment by uhlhosting** [comment]
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/6324047/78934912-0e3c0700-7aac-11ea-88cb-41638f0d5eae.png">
on coreos

**Comment by uhlhosting** [comment]
problem was solved, just one node failed at first to install the proper rpm, this leaded. to one virthandler to restart.
