### ISSUE TITLE
Broken links to qemu.weilnetz.de

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt.github.io#575]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Some of the links on the website are broken. kubevirt-io-periodic-link-checker reported following issue:

```
- ./_site/2018/KubeVirt-objects.html
  *  External link https://qemu.weilnetz.de/doc/qemu-doc.html#Block-device-options failed: 404 No error
  *  External link https://qemu.weilnetz.de/doc/qemu-doc.html#Debug_002fExpert-options failed: 404 No error
  *  External link https://qemu.weilnetz.de/doc/qemu-doc.html#Standard-options failed: 404 No error
rake aborted!
HTML-Proofer found 3 failures!
```

https://storage.googleapis.com/kubevirt-prow/logs/kubevirt-io-periodic-link-checker/1272155433666088960/build-log.txt?Expires=1592209133&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=h%2BD2EozkWkoolAev5%2F%2BTTNZlaTDtKUnJAVqxUL%2FOb%2Bo1IPsYmzSieAyp%2BbaNhvj0i%2BCzFnpSkLF4s0RZOFPWdzw5m7AjTNZn6pKK7o8NQabmr0z41RCGmvEYZN7sjtgY7TQXaqEO5WCB4RSnqKpuOCb83Dzhbb8JCQcYXaLV%2FPl5EUU%2FhU1N00uapSQTA5h%2FZHgH8DUJSnwOhpRsyB7%2FBuidGujneziYLxeLCULvxDGpCjz7r0n3ei57%2Firrk8VysfXUDeuIlweh9n0LRDxH77F%2BG4EGKRzERI%2BbRf45Eqqgwlsnz5z65yWmA3r25yEkL7WpSwF5H3OlEohv54NtEQ%3D%3D

**Comment by codificat** [comment]
Thanks for the report.

Looking at the affected blog post, it turns out that there are many more broken links there - mostly all the links to the docs :/

I'll look at why these are not being reported to begin with.
