### ISSUE TITLE
Bad formatting of automated release changelog blog post

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt.github.io#582]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:

The last automated release blog post (for v0.31.0) contains references to PR numbers and authors, and it does so in a suboptimal way: it misses proper formatting for that (e.g. links to the PRs, proper brackets...)

**What you expected to happen**:

A nicer presentation of the release changelog

**Anything else we need to know?**:

> URL where the problem can be found ...

https://kubevirt.io/2020/changelog-v0.31.0.html shows the (slightly) ugly format.
In comparison, the equivalent [v0.30.0](https://kubevirt.io/2020/changelog-v0.30.0.html) post does not contain PR or author information, but also no formatting issues related to that.

> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by mazzystr** [comment]
~/scripts/update_changelog.sh drives the generation of this page.  It's a bash script and probably at the end of it's scale.  It would be a nice exercise to port to gloang.

@fabiand  We spoke about having a more detailed and personal touch to the release.  It appears the kubevirt tag create message already contains the info but it is the script that is filtering out the data.

```
$ git -C build/kubevirt show v0.32.0
tag v0.32.0
Tagger: David Vossel <davidvossel@gmail.com>
Date:   Tue Aug 11 19:21:56 2020 +0000

This release follows v0.31.0 and consists of 189 changes, contributed by 26 people, leading to 460 files changed, 17395 insertions(+), 19058 deletions(-).
v0.32.0 is a promotion of release candidate v0.32.0-rc.2 which was originally published 2020-08-10
The source code and selected binaries are available for download at: https://github.com/kubevirt/kubevirt/releases/tag/v0.32.0.

The primary release artifact of KubeVirt is the git tree. The release tag is
signed and can be verified using `git tag -v v0.32.0`.

Pre-built containers are published on Docker Hub and can be viewed at: <https://hub.docker.com/u/kubevirt/>.

Notable changes
---------------

- [PR #3921][vladikr] use correct memory units in libvirt xml
- [PR #3893][davidvossel] Adds recurring period that resyncs virt-launcher domains with virt-handler
- [PR #3880][sgarbour] Better error message when input parameters are not the expected number of parameters for each argument. Help menu will popup in case the number of parameters is incorrect.
- [PR #3785][xpivarc] Vcpu wait metrics available
- [PR #3642][vatsalparekh] Add a way to update VMI Status with latest Pod IP for Masquerade bindings
- [PR #3636][ArthurSens] Adds kubernetes metadata.labels as VMI metrics' label
- [PR #3825][awels] Virtctl now prints error messages from the response body on upload errors.
- [PR #3830][davidvossel] Fixes re-establishing domain notify client connections when domain notify server restarts due to an error event.
- [PR #3778][danielBelenky] Do not emit a SyncFailed event if we fail to sync a VMI in a final state
- [PR #3803][andreabolognani] Not sure what to write here (see above)
- [PR #2694][rmohr] Use native go libraries for selinux to not rely on python-selinux tools like semanage, which are not always present.
- [PR #3692][victortoso] QEMU logs can now be fetched from outside the pod
- [PR #3738][enp0s3] Restrict creation of VMI if it has labels that are used internally by Kubevirt components.
- [PR #3725][danielBelenky] The tests binary is now part of the release and can be consumed from the GitHub rele
```

I would be perfectly pleased with this data being advertised on the release page.  

We could easily extend this script to include GitHub pull and user profile url's.  That functionality should live in this script ... not in the git log.

**Comment by mazzystr** [comment]
@codificat  On thinking about formatting changes for the page... I think it should be an enhancement not a bug.

**Comment by codificat** [comment]
Fair enough, let's update to
/kind enhancement
