### ISSUE TITLE
ror: unable to decode "vm.yaml": no kind "VirtualMachine" is registered for version "kubevirt.io/v1alpha3"

### ISSUE THREAD

**Issue by Roberto-89** [kubevirt/kubevirt.github.io#584]
I followed the steps in "Easy install using minikube" to deploy Kubevirt in a Rancher k8s cluster. All of the pods are up and running 
kubectl --context production-k8s-chedprd01  get pods -n kubevirt
NAME                               READY     STATUS    RESTARTS   AGE
virt-api-56f8dd88fb-6stvp          1/1       Running   0          20h
virt-api-56f8dd88fb-t66c6          1/1       Running   0          20h
virt-controller-5fccd9bbc6-hpc6c   1/1       Running   0          57m
virt-controller-5fccd9bbc6-lgrq2   1/1       Running   0          56m
virt-handler-8f2qd                 1/1       Running   0          47m
virt-handler-b8c4h                 1/1       Running   1          5d
virt-handler-vv2g6                 1/1       Running   1          5d
virt-operator-7bb96476c-h4ddk      1/1       Running   0          20h
virt-operator-7bb96476c-l446h      1/1       Running   1          20h

However when starting the next lab "Use KubeVirt" I can't deploy a VM. When I attempt to apply the vm.yaml file I get the following error. 

error: unable to decode "vm.yaml": no kind "VirtualMachine" is registered for version "kubevirt.io/v1alpha3"

Any help would be appreciated as I am new to k8s and kubevirt.

**Comment by mazzystr** [comment]
Hi @Roberto-89 I am happy to meet you in [slack](https://app.slack.com/client/T09NY5SBT/C8ED7RKFE) and help you through this.

**Comment by Roberto-89** [comment]
I deleted kubevirt from the cluster and recreated it from scratch. I was able to deploy the VM after the rebuild. 

Thank you

**Comment by mazzystr** [comment]
@Roberto-89  Sorry for taking so long to get back with you.  Glad to hear that you were successful. 

Also note that we updated the "[Easy install using minikube](https://kubevirt.io/quickstart_minikube/)" lab.  Hopefully the update better reflects reality.

We should be publishing a "Easy install using Rancher K3S" lab within the month.  That task is now at the top of our backlog.
