### ISSUE TITLE
Enhance RSS headers

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#585]
/kind enhancement

RSS generation headers not just for main site, but for tags, etc so users can follow tags of interest (releases, specific author, etc)

Are we even generating RSS feeds?  I see no indication

**Comment by matthewcarleton** [comment]
I'm a bit out of the loop with RSS these days. Is it still a useful feature?

**Comment by mazzystr** [comment]
/remove-lifecycle rotten
/reopen

Re RSS's usefuleness... I'm not an RSS guy at all.  I think I took this from an adhoc conversation or another issue.  We can have an official discussion in the near future regarding the usefulness of RSS in relation to the website.
