### ISSUE TITLE
Disqus alternative

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#587]
/kind enhancement

From TODO: Investigate alternatives to Disquss (other projects doing this research: https://github.com/Pelican-Elegant/elegant/issues/288)

**Comment by matthewcarleton** [comment]
@mazzystr have you guys come to a conclusion on what you'd like to replace it with? I'm not very educated on the alternatives to Disqus.

**Comment by matthewcarleton** [comment]
I would suggest that we consider removing comments on the blog altogether. It opens the site up to a new level of moderation and as you can see on the site now there has been very little engagement via comments on the blog.

**Comment by mazzystr** [comment]
+1 to removing Disqus.  I block disqus on my home network anyway so I see errors at the bottom of the blog pages.

**Comment by mazzystr** [comment]
Next step is to reach out to the community (kubevirt-dev) to see if anyone has any objections to removing Disqus and replacing with a footer / link to the community page.

**Comment by mazzystr** [comment]
Email sent ... https://mail.google.com/mail/u/0/#label/Linux%2FKubeVirt/KtbxLzGHjXqlVSkTWSDvVSwmDrNptjBBZL
