### ISSUE TITLE
Integrate the Autodemo video in the front page

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#588]
/kind enhancement

We recently received and published in YouTube a professionally made video with an overview of KubeVirt:

https://youtu.be/uusM5SyK-vc

We would like to feature this video prominemptly in the kubevirt.io website, probably embedding it in the homepage or similar, in a way that is not too disruptive but that is easy to access at the same time.

We suspect that this involves some redesign of the home page, which would benefit from assistance from the design team.

Acceptance criteria:
* The video is included in the main webpage
* The changes are published
* The video autoplays itself when the kubevirt.io page is visited

Ref: [KNIECO-1728](https://issues.redhat.com/browse/KNIECO-1728)

**Comment by codificat** [comment]
This was addressed via #562...

I believe the acceptance criteria listed here were the initial proposal, but it was then deemed better not to auto-play the video every time, or even have it always take precious homepage space, so the design kept it easily reachable through a prominent button, but still not present by default.

Should we re-review that and have the video permanently present and auto-play? (personally I prefer how it looks currently, but more opinions welcome)

**Comment by matthewcarleton** [comment]
+1 to what @codificat is saying I propose we close this issue.

**Comment by mazzystr** [comment]
+1 to closing with no work involved
