### ISSUE TITLE
Blog/lab side bar take too much screen real estate

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#590]
/kind bug

Goal: Adjust side menu

Problem: Side menu consumes 30% of the window real estate

Why is this important: The page looks right side heavy and there is a lot of dead space.

 
This should be fixed easily enough with a css adjustment

Ref: [KNIECO-2251](https://issues.redhat.com/browse/KNIECO-2251)

**Comment by mazzystr** [comment]
Fabian is not fond of the current borders or the proposed borders on his wide screen monitor with browser set to full screen mode
![Fabian-Curreent-KubeVirt Quickstart with Minikube KubeVirt io(1)](https://user-images.githubusercontent.com/2479463/89935747-884ddb00-dbc7-11ea-850e-30bc55dd819b.png)
![Fabian-Proposed-Minikube KubeVirt addon KubeVirt io](https://user-images.githubusercontent.com/2479463/89935755-8ab03500-dbc7-11ea-8170-0857922f58ee.png)

**Comment by mindreeper2420** [comment]
@mazzystr What borders are you referring to? At a certain point, accounting for ultrawide monitors (I have a 3440x1440 one) becomes not worth the effort.

If possible, it'd be great to know what the average user has for screen widths (if there is any tracking, that would help). If not, I'd go with what Bootstrap uses/the accepted viewports are. The largest Bootstrap currently truly 'cares' about is `1200px` wide.

**Comment by mazzystr** [comment]
@matthewcarleton says there's nothing to be done with this issue.  Closing now.
