### ISSUE TITLE
Try it! front page link should be swung to Katacoda lab

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#593]
> /kind enhancement

Try it! front page link should be swung to Katacoda lab.  New users should be able to get started in minutes not scratch their head with the existing quick start guide.

Loosely based upon [KNIECO-2253](https://issues.redhat.com/browse/KNIECO-2253)

**Comment by matthewcarleton** [comment]
@mazzystr can you provide the link you want here

**Comment by mazzystr** [comment]
I'm not sure what I was thinking here.  Let's just close this.
