### ISSUE TITLE
quickstart_minikube page links to localhost:24000

### ISSUE THREAD

**Issue by haslersn** [kubevirt/kubevirt.github.io#625]
See for instance: https://github.com/kubevirt/kubevirt.github.io/blob/12cc61d7d16bd7947c3797849c124f32ff0ed164/quickstart_minikube/index.html#L409

Is the link to `http://localhost:24000/labs/kubernetes/lab1` intentional? I think it should be a relative link in order to resolve to `https://kubevirt.io/labs/kubernetes/lab1`.

**Comment by mazzystr** [comment]
Amazing how these things get through local testing, peer review, and CI!

Thanks for this catch.

You can create a pull request to fix now and I'll tag lgtm/approve or I'll
take care of it in the morning.

Thanks,
/Chris
