### ISSUE TITLE
How to use TFTP server?

### ISSUE THREAD

**Issue by sanzende** [kubevirt/kubevirt.github.io#639]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
> Uncomment only one, leave it on its own line:
>
> /kind bug
#> /kind enhancement
**What happened**:
I followed the instructions to add to my TFTP server and the bootfile using the example in this link
https://kubevirt.io/user-guide/#/creation/interfaces-and-networks

The request is invalid: 
* : spec.domain.devices.interfaces.bootFileName in body is a forbidden property
* : spec.domain.devices.interfaces.tftpServerName in body is a forbidden property

**What you expected to happen**:
The VM creation should have started looking for TFTP server. 

**Anything else we need to know?**:
It would be great to have any end to end example in the documentation on how to configure tftp server and how to use its details and bootfile name and all in the VM spec.

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by mazzystr** [comment]
@sanzende Would you mind relocating this issue to kubevirt/kubevirt for greater visibility to the community?   We use this repo strictly for website (https://kubevirt.io) issues.

**Comment by sanzende** [comment]
Thanks Mazzy. I did not know about that before opened an issue here. I have already opened an issue and got a response. 

Regards
Sandeep
