### ISSUE TITLE
Job kubevirt-io-periodic-link-checker is failing since 2020-11-10

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt.github.io#651]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

> /kind enhancement

/triage build-watcher

**What happened**:

Job [kubevirt-io-periodic-link-checker](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/kubevirt-io-periodic-link-checker/1325818670215073792) is failing for a couple days now, posting to slack channel coreos/kubevirt-ci-monitoring 

**What you expected to happen**:

**Anything else we need to know?**:

@mazzystr not sure if you are already aware, didn't find anything here, so feel free to close with mention of the existing one.

> URL where the problem can be found ...

 https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/kubevirt-io-periodic-link-checker/1325818670215073792

> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by mazzystr** [comment]
It's not a bug with link-checker.  Those are legit broken links.  I'll get them fixed.  

@dhiller Is there anyway that job can be adjusted so the community team gets notified?  Maybe change or add coreos/#eko channel?

**Comment by dhiller** [comment]
> It's not a bug with link-checker. Those are legit broken links. I'll get them fixed.
> 
> @dhiller Is there anyway that job can be adjusted so the community team gets notified? Maybe change or add coreos/#eko channel?

@rmohr something like this would work, right? https://github.com/kubevirt/project-infra/pull/692
