### ISSUE TITLE
Markdown files are not being linted

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#652]
/kind bug

**What happened**:
I ran a quick linter against the website markdown.  The linter came up with 2900 warnings...
* line length
* no language in fenced code blocks
* bare urls
* Fenced code blocks should be surrounded by blank lines
* Multiple top level headings
* Inline HTML
* Dollar signs used before commands
* Heading levels should only increment by one level at a time

**What you expected to happen**:
I expected some warnings since we never linted before but ... wow!

Linting tool used was (https://github.com/igorshubovych/markdownlint-cli)

**Comment by tylerauerbeck** [comment]
@mazzystr I actually just put something in place for this in one of my own repos recently. Are you looking for any help to get this cleaned up?

**Comment by mazzystr** [comment]
@tylerauerbeck I would most welcome assistance with this.  Let's start with
a new Makefile target then I can help you with an addition to CI.

**Comment by tylerauerbeck** [comment]
@mazzystr Opened #765 as I saw this was still open (and was going stale again) and I saw that none of the previous PR's had been merged. Tried to take some of the notes from the others as a good starting point. Is the idea to have the linter merged first and then address the lint errors?
