### ISSUE TITLE
Broken Link [404 Error]

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt.github.io#670]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

Broken link on the website for user guide (https://kubevirt.io/user-guide/#/Appendix/Contributing) Getting 404 error. 

> URL where the problem can be found ...
https://kubevirt.io/user-guide/#/Appendix/Contributing

**Comment by codificat** [comment]
This was addressed by kubevirt/user-guide#377

Thanks!
/close
