### ISSUE TITLE
vm appears running, but cant console, also seems ip keeps changing

### ISSUE THREAD

**Issue by outbackdingo** [kubevirt/kubevirt.github.io#691]
controller-0:~$ kubectl get vmis
NAME     AGE   PHASE     IP               NODENAME
testvm   64s   Running   172.16.192.163   controller-0
controller-0:~$ virtctl console testvm
Successfully connected to testvm console. The escape sequence is ^]

You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF
controller-0:~$ virtctl console testvm
Successfully connected to testvm console. The escape sequence is ^]

You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF
controller-0:~$ kubectl get vmis
NAME     AGE   PHASE     IP               NODENAME
testvm   77s   Running   172.16.192.163   controller-0
controller-0:~$ virtctl console testvm
Successfully connected to testvm console. The escape sequence is ^]

You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF
kubectl get vmis
NAME     AGE    PHASE     IP               NODENAME
testvm   2m2s   Running   172.16.192.191   controller-0

**Comment by mazzystr** [comment]
@outbackdingo This repo is for kubevirt.io website development.  Would you mind recreating this issue in kubevirt/kubevirt?  It will get much more attention.

**Comment by mazzystr** [comment]
No response within 15 days.  Closing issue.
