### ISSUE TITLE
vmctl client tool is deprecated

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#696]
vmctl client tool is deprecated and removed per https://github.com/kubevirt/user-guide/pull/395

Please review labs and non-blog pages and replace cases of `vmctl` use

Please create blog post with simple notification

**Comment by mazzystr** [comment]
@davidvossel Are you able to take this on?

**Comment by codificat** [comment]
There are no references to `vmctl` in the website AFAICT.
/close
