### ISSUE TITLE
Blog post for using virtual machines with Intel vGPU's

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#711]
/kind enhancement

https://github.com/kubevirt/kubevirt/pull/5215 was recently merged.  

It would be great to create a blog post detailing real world use.  

It would be +1 if screenshots of [a|h]top are added detailing how performance is improved using this feature.

It would be ++1 if a cost/benefit/depreciation analysis can be done showing Intel GPU vs others.

**Comment by xphyr** [comment]
I will be happy to pick this up.  Let me take a look at how the web pages are created for this site and start some work on a post about the use of the Intel GPUs. I will make progress this week and post back here when I have something to share.

**Comment by mazzystr** [comment]
Clone this repo
Create new blog markdown under `./_posts`
Build prereq images `make build_image_yaspeller && make build_image_casperjs`
Test locally using `make run`
Test syntax with `make check_spelling` and `make check_links`
Create a pull req.  
The community will review and approve :)

I guess we need to update the README, hm?? New issues! ;)

**Comment by xphyr** [comment]
I started by following these instructions: https://github.com/kubevirt/kubevirt.github.io/blob/source/GUIDELINES.md. I made a fork, created a branch and I also installed the pre-commit hooks. That being said, while attempting to store my work on my own fork the pre-commit hooks are failing.

```
An unexpected error has occurred: CalledProcessError: command: ('/home/markd/.cache/pre-commit/repoz7ew65pp/node_env-default/bin/node', '/home/markd/.cache/pre-commit/repoz7ew65pp/node_env-default/bin/npm', 'install')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm notice
    npm notice New minor version of npm available! 7.6.3 -> 7.7.0
    npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.7.0>
    npm notice Run `npm install -g npm@7.7.0` to update!
    npm notice
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR!
    npm ERR! While resolving: prettier@1.19.1
    npm ERR! Found: @angular/compiler@8.2.13
    npm ERR! node_modules/@angular/compiler
    npm ERR!   @angular/compiler@"8.2.13" from the root project
    npm ERR!
    npm ERR! Could not resolve dependency:
    npm ERR! peer @angular/compiler@"^6.0.0 || ^7.0.0" from angular-estree-parser@1.1.5
    npm ERR! node_modules/angular-estree-parser
    npm ERR!   angular-estree-parser@"1.1.5" from the root project
    npm ERR!
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR!
    npm ERR! See /home/markd/.npm/eresolve-report.txt for a full report.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/markd/.npm/_logs/2021-03-23T19_09_29_025Z-debug.log
```

This is running on a Fedora workstation that is fully patched/up to date. Suggestions on how to move forward would be appreciated.  Based on your above instructions, perhaps the pre-commit hooks are no longer needed?

**Comment by mazzystr** [comment]
Whoa nelly ... GUIDELINES.md is very out of date too.  :/

**Comment by xphyr** [comment]
I think the Makefile also has some issues.... `make run` fails, but I updated the Makefile to use the command in the main readme, and things are looking better. I may try and make a few other Makefile changes to see if I can clean this up a little. Can you confirm that the pre-commit hooks are no longer needed.

**Comment by mazzystr** [comment]
re Makefile ... sounds good.  I test with Fedora and and podman 2.2.
podman 3.0 is out now.  I haven't had time to circle and reverify things.

re pre-commit hooks ... They're definitely not needed.  I haven't used them
at all in the year I've been on KubeVirt.

**Comment by xphyr** [comment]
I am working on this here: https://github.com/xphyr/kubevirt.github.io/tree/issue%23711 if anyone is curious.

**Comment by xphyr** [comment]
@mazzystr I think this can now be closed out.
