### ISSUE TITLE
Prow job to periodically build website img

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#716]
Img building is getting streamlined via https://github.com/kubevirt/kubevirt.github.io/issues/715

Once complete Prow should periodically build the website img and push to KubeVirt org in Docker Hub

**Comment by tylerauerbeck** [comment]
@mazzystr Is this related to https://github.com/kubevirt/project-infra/pull/1332 ? Or are those two different?

**Comment by mazzystr** [comment]
I think kubevirt/project-infra#1332 is no longer valid since the
functionality was implemented via a different pull req created by dhiller.

This issue is to get a periodic job created so the post submit job can also
run like a cron job.  This allows the website to have scheduled publishing
of blogs posts or other website updates.
