### ISSUE TITLE
Create a blog for kubevirt Code Code Walkthrough

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt.github.io#732]
Create a blog for kubevirt Code Code Walkthrough

**Comment by mazzystr** [comment]
@davidvossel What do you think about a special meeting on the KubeVirt zoom meeting?  We can record then blog and post to YouTube.

**Comment by davidvossel** [comment]
> @davidvossel What do you think about a special meeting on the KubeVirt zoom meeting? We can record then blog and post to YouTube.

That might make sense. One concern I have is that our code base is constantly in flux. Things get moved around all the time. For example, I could cover the location for our API being in the `staging` directory, then we might move that around in the future. 

I might be able to talk about the structure in broader terms though.

@ansijain What kind of information would you find useful here?

**Comment by ansijain** [comment]
Thank you for the response.

I am new to kubevirt community. I want to get more familiar with the code base so that I can start code contribution.

It would be great if you help me with structure or any relevant information that is helpful for contribution.

**Comment by davidvossel** [comment]
@ansijain  have you checked out our getting started [1] and contributing [2] guides? Have those been helpful with onboarding ?

1. https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md
2. https://github.com/kubevirt/kubevirt/blob/master/CONTRIBUTING.md

**Comment by ansijain** [comment]
@davidvossel yes I have gone through these documents. It was really helpful.
But with this I am expecting some overview on code side. If that is possible.

**Comment by davidvossel** [comment]
> @davidvossel yes I have gone through these documents. It was really helpful.
> But with this I am expecting some overview on code side. If that is possible.

possibly ,I'm unsure about the scope of what we're talking about here though. Do you have an example of another project that provides the kind of code walk-through you're interested in?

**Comment by ansijain** [comment]
@davidvossel  
I am expecting walk-through something like in this video [1] and blog [2]

[1] https://developer.ibm.com/conferences/oscc_become_a_kubernetes_contributor/kubernetes_scheduler_code_walkthrough/
[2] https://developer.ibm.com/components/kubernetes/articles/a-tour-of-the-kubernetes-source-code/

**Comment by davidvossel** [comment]
> I am expecting walk-through something like in this video [1] and blog [2]

Thanks, I'll give this some thought. It might take some time before I can look at this closer.

**Comment by mazzystr** [comment]
May this diagram helps?

https://kubernetes.slack.com/files/U2WUVHD6Y/F0221FWU6KW/kubevirt_create_vmi_seq_diagram.jpg

**Comment by ansijain** [comment]
Yes this sequence diagram is helpful.
