### ISSUE TITLE
Website blog/gallery/labs/community pages not rendering correctly

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#775]
/kind bug

**What happened**:
https://kubevirt.io/blogs/
https://kubevirt.io/gallery/
https://kubevirt.io/labs/
https://kubevirt.io/community/

...pages are broke.  Please repair.

Likely related to the default template from https://github.com/kubevirt/kubevirt.github.io/pull/762/files

**What you expected to happen**:
Pages should render correctly

**Anything else we need to know?**:
Nope

**Comment by kobi86** [comment]
Hi @mazzystr, 
Maybe [this](https://github.com/kobi86/CheckUrl) can help is some way .
I you want me to adjust something to make it work with our project please let me know :)
