### ISSUE TITLE
Obtain permission to advertise Google on index page

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#783]
/kind enhancement

**What happened**:
Let's find the Google representative and obtain explicit permission to advertise.  

**What you expected to happen**:

**Anything else we need to know?**:
Add logo [here](https://github.com/kubevirt/kubevirt.github.io/tree/master/assets/images/adopters)
Add data [here](https://github.com/kubevirt/kubevirt.github.io/blob/master/_data/adopters.yml)

**Comment by jberkus** [comment]
I can ask, but how do we know that Google is a user?

**Comment by mazzystr** [comment]
They're among us.  I've spoken to one regarding but was told not yet.  The
topic might be better approached from the OSPO level.

**Comment by jberkus** [comment]
Since we don't have a name of anyone at Google who definitely uses Kubevirt, I suggest closing this for now.
