### ISSUE TITLE
Obtain permission to advertise NEC on index page

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#792]
/kind enhancement

**What happened**:
Let's find the NEC representative and obtain explicit permission to advertise.  

**What you expected to happen**:

**Anything else we need to know?**:
Add logo [here](https://github.com/kubevirt/kubevirt.github.io/tree/master/assets/images/adopters)
Add data [here](https://github.com/kubevirt/kubevirt.github.io/blob/master/_data/adopters.yml)

**Comment by gmannos** [comment]
Hi, I am from NEC and will bring/discuss this to our team about the possibility of using log/data.
