### ISSUE TITLE
Obtain permission to advertise ARM on index page

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#812]
/kind enhancement

**What happened**:
Let's find the ARM representative and obtain explicit permission to advertise.  

**What you expected to happen**:

**Anything else we need to know?**:
Add logo [here](https://github.com/kubevirt/kubevirt.github.io/tree/master/assets/images/adopters)
Add data [here](https://github.com/kubevirt/kubevirt.github.io/blob/master/_data/adopters.yml)

**Comment by mazzystr** [comment]
https://github.com/kubevirt/kubevirt/pull/6704

**Comment by mazzystr** [comment]
arm requests that we follow their corporate logo standards as detailed here ..... https://www.arm.com/company/policies/trademarks/guidelines-corporate-logo

**Comment by zhlhahaha** [comment]
We have gotten Arm permission to advertise the Arm logo on the KubeVirt website.
