### ISSUE TITLE
website ssl certificate has expired

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#830]
/kind bug

**What happened**:
website ssl certificate has expired

**What you expected to happen**:

**Anything else we need to know?**:

> URL where the problem can be found ...
https://kubevirt.io

**Comment by cwilkers** [comment]
Hey @mazzystr I guess somebody rescued us in June, because it's currently up to date, but it would be nice to know who did that because it expires again in September.

**Comment by cwilkers** [comment]
It looks like the cert is being renewed more proactively now:

Issued On	Monday, August 22, 2022 at 2:18:05 AM
Expires On	Sunday, November 20, 2022 at 1:18:04 AM
