### ISSUE TITLE
Make build_img fails to build website locally

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/kubevirt.github.io#850]
/kind bug

**What happened**:
Trying to perform local build of kubevirt.github.io/ as per https://github.com/kubevirt/kubevirt.github.io#test-work
$make build_img
Currently failing - my guess is around line 20 of the Dockerfile. 

**What you expected to happen**:
Make command completes and I can build website locally to review changes. 

**Anything else we need to know?**:
Running Fedora 34
Here is the output from the end of the yum pkg install. Perhaps of interest, for the first line in the ERROR REPORT TEMPLATE, I've had both 
> Gem::Package::FormatError: package metadata is missing in /usr/share/gems/cache/colorator-1.1.0.gem
and 
> Gem::Package::FormatError: package metadata is missing in /usr/share/gems/cache/forwardable-extended-2.6.0.gem

I *think* the difference was between not setting anything and explicitly setting podman using
```
$ export CONTAINER_ENGINE=podman
$ export BUILD_ENGINE=podman
```
as per the README (well... using podman instead of docker)
Hopefully this is enough info and someone can make more sense of this than I can!
Output:
> ...                        
>   xz-5.2.5-9.fc34.x86_64                                                        
>   xz-devel-5.2.5-9.fc34.x86_64                                                  
>   zip-3.0-28.fc34.x86_64                                                        
>   zlib-devel-1.2.11-26.fc34.x86_64   
>   
> Complete!
> npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> /usr/local/bin/casperjs -> /usr/local/lib/node_modules/casperjs/bin/casperjs
> /usr/local/bin/markdownlint -> /usr/local/lib/node_modules/markdownlint-cli/markdownlint.js
> /usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs-prebuilt/bin/phantomjs
> /usr/local/bin/yaspeller -> /usr/local/lib/node_modules/yaspeller/bin/yaspeller
> 
> > phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/phantomjs-prebuilt
> > node install.js
> 
> Considering PhantomJS found at /usr/local/bin/phantomjs
> Looks like an `npm install -g`
> Could not link global install, skipping...
> Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
> Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
> Receiving...
> 
> Received 22866K total.
> Extracting tar contents (via spawned process)
> Removing /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
> Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1655973144857/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
> Writing location.js file
> Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
> + markdownlint-cli@0.31.1
> + phantomjs-prebuilt@2.1.16
> + casperjs@1.1.4
> + yaspeller@8.0.1
> added 147 packages from 149 contributors in 16.492s
> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
> installing your bundle as root will break this application for all non-root
> users on this machine.
> Fetching gem metadata from https://rubygems.org/..........
> Resolving dependencies...
> Using rake 13.0.6
> Fetching asciidoctor 2.0.17
> Using bundler 2.2.33
> Fetching colorator 1.1.0
> Fetching concurrent-ruby 1.1.10
> Fetching http_parser.rb 0.8.0
> Fetching ffi 1.15.5
> Fetching public_suffix 4.0.7
> Fetching forwardable-extended 2.6.0
> Fetching eventmachine 1.2.7
> 
> Retrying download gem from https://rubygems.org/ due to error (2/4): Encoding::UndefinedConversionError "\x8B" from ASCII-8BIT to UTF-8
> 
> Fetching mercenary 0.4.0
> Fetching racc 1.6.0
> 
> 
> 
> Fetching parallel 1.22.1
> 
> Fetching rainbow 3.1.1
> Fetching yell 2.2.2
> 
> Fetching rb-fsevent 0.11.1
> Fetching rexml 3.2.5
> 
> 
> Fetching liquid 4.0.3
> Fetching rouge 3.29.0
> 
> Fetching safe_yaml 1.0.5
> 
> 
> 
> Fetching unicode-display_width 1.8.0
> Fetching jekyll-paginate 1.1.0
> Fetching nuggets 1.6.1
> 
> Fetching premonition 2.0.1
> 
> Fetching unicode_utils 1.4.0
> 
> 
> Fetching webrick 1.7.0
> 
> 
> 
> 
> 
> 
> 
> --- ERROR REPORT TEMPLATE -------------------------------------------------------
> 
> ```
> Gem::Package::FormatError: package metadata is missing in /usr/share/gems/cache/colorator-1.1.0.gem
>   /usr/share/rubygems/rubygems/package.rb:670:in `verify_files'
>   /usr/share/rubygems/rubygems/package.rb:596:in `block (2 levels) in verify'
>   /usr/share/rubygems/rubygems/package/tar_reader.rb:27:in `new'
>   /usr/share/rubygems/rubygems/package.rb:593:in `block in verify'
>   /usr/share/rubygems/rubygems/package/file_source.rb:29:in `open'
>   /usr/share/rubygems/rubygems/package/file_source.rb:29:in `with_read_io'
>   /usr/share/rubygems/rubygems/package.rb:592:in `verify'
>   /usr/share/rubygems/rubygems/package.rb:573:in `spec'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/rubygems_integration.rb:250:in `spec_from_gem'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:167:in `install'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:54:in `install'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/worker.rb:62:in `apply_func'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/worker.rb:57:in `block in process_queue'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `loop'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `process_queue'
>   /usr/share/gems/gems/bundler-2.2.33/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
> ```
> 
> ## Environment
> 
> ```
> Bundler       2.2.33
>   Platforms   ruby, x86_64-linux
> Ruby          3.0.4p208 (2022-04-12 revision 3fa771ddedac25560be57f4055f1767e6c810f58) [x86_64-linux]
>   Full Path   /usr/bin/ruby
>   Config Dir  /etc
> RubyGems      3.2.33
>   Gem Home    /usr/share/gems
>   Gem Path    /root/.local/share/gem/ruby:/usr/share/gems:/usr/local/share/gems
>   User Home   /root
>   User Path   /root/.local/share/gem/ruby
>   Bin Dir     /usr/bin
> OpenSSL       
>   Compiled    OpenSSL 1.1.1n  FIPS 15 Mar 2022
>   Loaded      OpenSSL 1.1.1n  FIPS 15 Mar 2022
>   Cert File   /etc/pki/tls/cert.pem
>   Cert Dir    /etc/pki/tls/certs
> Tools         
>   Git         2.34.3
>   RVM         not installed
>   rbenv       not installed
>   chruby      not installed
> ```
> 
> ## Bundler Build Metadata
> 
> ```
> Built At          2022-06-23
> Git SHA           unknown
> Released Version  false
> ```
> 
> ## Gemfile
> 
> ### Gemfile
> 
> ```ruby
> Encoding.default_external = Encoding::UTF_8
> Encoding.default_internal = Encoding::UTF_8
> 
> source "https://rubygems.org"
> 
> gem "jekyll"
> gem "rake"
> gem "jekyll-paginate"
> gem "jekyll-redirect-from"
> gem "html-proofer"
> gem "jekyll-asciidoc"
> gem "jekyll-feed"
> gem "jekyll-sitemap"
> gem "premonition", "~> 2.0.1"
> gem "jekyll-tagging"
> gem "jekyll-diagrams"
> gem "jekyll-inline-svg"
> gem "unicode_utils"
> gem "webrick"
> ```
> 
> ### Gemfile.lock
> 
> ```
> <No /src/Gemfile.lock found>
> ```
> 
> --- TEMPLATE END ----------------------------------------------------------------
> 
> Unfortunately, an unexpected error occurred, and Bundler cannot continue.
> 
> First, try this link to see if there are any existing issue reports for this error:
> https://github.com/rubygems/rubygems/search?q=package+metadata+is+missing+in+%2Fusr%2Fshare%2Fgems%2Fcache%2Fcolorator-1.1.0.gem&type=Issues
> 
> If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
> Error: error building at STEP "RUN yum update -y &&     yum install -y @development-tools       langpacks-en glibc-all-langpacks redhat-rpm-config openssl-devel gcc-c++       tar jq bzip2       nodejs npm python37 python3-pip ruby ruby-devel rubygems rubygems-devel       rubygem-bundler rubygem-json rubygem-nenv rubygem-rake &&     alternatives --install /usr/bin/python python /usr/bin/python3 1 &&     npm config set user 0 &&     npm config set unsafe-perm true &&     npm install -g markdownlint-cli casperjs phantomjs-prebuilt yaspeller &&     cd /src && bundle install && bundle update && cd &&     gem list &&     rpm -e --nodeps libX11 libX11-common libXrender libXft libusbx xml-common &&     yum erase -y @development-tools gcc gtk2 subversion qt5-srpm-macros git       xkeyboard-config shared-mime-info qrencode-libs memstrack mod_lua       redhat-rpm-config openssl-devel ruby-devel rubygems-devel glibc-doc       nodejs-docs rubygem-rdoc dracu glibc-all-langpacks vim-minimal tar setup       diffutils acl npm pigz ncurses mkpasswd libXau bzip2 xz python3-pip jq &&     dnf clean all &&     rm -rf /root/{.bundle,.config,.npm,anaconda*,original-ks.cfg} /tmp/phantomjs /var/cache/yum": error while running runtime: exit status 1

**Comment by cwilkers** [comment]
I was able to update the Dockerfile locally to create a working image from Fedora 36 (which also required a Makefile adjustment to run the local webpage copy. I'll create some PRs to adjust here and in project-infra, but I will need a second pair of eyes to make sure the updates do not damage part of our CI/CD pipeline.
