### ISSUE TITLE
had volume node affinity conflic

### ISSUE THREAD

**Issue by shorif2000** [kubevirt/kubevirt.github.io#872]
/kind bug

**What happened**:
Following this https://kubevirt.io/2019/How-To-Import-VM-into-Kubevirt.html and https://kubevirt.io/user-guide/operations/containerized_data_importer/ with help of https://www.datree.io/resources/kubernetes-troubleshooting-fixing-persistentvolumeclaims-error#anchor0 but cannot seem to deploy simple cirros image. there seems to be instructions missing.

keep getting error 
```
0/1 nodes are available: 1 node(s) had volume node affinity conflict. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```
**What you expected to happen**:
deployed cirros image

**Anything else we need to know?**:

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by cwilkers** [comment]
Apologies for missing this so long, we don't usually monitor the website's repo for issues against KubeVirt or CDI.
Can you give details on the Kubernetes cluster you're trying this on?
What kind of storage provider are you using?
Are you able to create a PVC that binds to a PV, then successfully run a Pod attached to it?
On which component are you seeing the above error?
Could you provide YAML for your PVC and/or DataVolume?
