### ISSUE TITLE
KubeVirt Upgrade lab has old version references

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/kubevirt.github.io#874]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The upgrade lab has the 'v0.20.1' and 'v0.21.0' versions hardcoded. This version is pretty old by today's standard, as we are currently on v0.57.0 (with v0.58.0 releasing very soon).

**What you expected to happen**:
We should update the versions used to be more in keeping with modern times. As of time of writing that would be upgrading from 'v0.56.1' to 'v0.57.0'.

In addition, there's references to changes implemented from 'v0.17.0' which are no longer relevant. These could be removed. 

Stretch goal: Considering the versions used, this lab could probably benefit from an end-to-end test runthrough to confirm that the workflow has not changed since this lab was last updated. This can be done on most laptop/machines using the [minikube](https://kubevirt.io/quickstart_minikube/) or [kind](https://kubevirt.io/quickstart_kind/) quickstarts. Please raise additional issues as needed. 

**Anything else we need to know?**:
This is the file: 
https://github.com/kubevirt/kubevirt.github.io/blob/main/labs/kubernetes/lab3.md

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...
You can see the published lab on the website here: https://kubevirt.io/labs/kubernetes/lab3.html

**Comment by dipesh-rawat** [comment]
@aburdenthehand Can you please assign this to me, so I can work to update the old version references.

**Comment by hindu-muppala** [comment]
I am interested in solving this bug. Can @aburdenthehand assign this issue to me?

**Comment by aburdenthehand** [comment]
@hindu-muppala Thank you very much for taking care of this!
