### ISSUE TITLE
The docs.kubevirt.io subdomain should redirect to kubevirt.io/docs/

### ISSUE THREAD

**Issue by gszasz** [kubevirt/kubevirt.github.io#88]
Since the new [KubeVirt Documentation](http://kubevirt.io/docs/) was already reconciled, the http://docs.kubevirt.io subdomain should redirect to http://kubevirt.io/docs/ instead of http://kubevirt.io/user-guide/ 

We need to point KubeVirt users to the most recent documentation resource as [KubeVirt User Guide](http://kubevirt.io/user-guide/) is going to be deprecated soon.

**Comment by gszasz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feedback on KubeVirt.io](https://trello.com/c/OAgmQKO5/172-feedback-on-kubevirtio)

**Comment by karmab** [comment]
addressed in https://github.com/kubevirt/kubevirt.github.io/pull/137
