### ISSUE TITLE
adopters.py doesn't work due to missing images

### ISSUE THREAD

**Issue by shurup** [kubevirt/kubevirt.github.io#889]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Running `_data/adopters.py` fails with a traceback:
```
Traceback (most recent call last):
  File "/home/shurup/.workspace/kubevirt.github.io/_data/adopters.py", line 76, in <module>
    "logo": logo(line[1].replace(' ','')),
  File "/home/shurup/.workspace/kubevirt.github.io/_data/adopters.py", line 36, in logo
    return result[0]
```
It happens due to missing images in `assets/images/adopters/` directory. To be more precise, the following images (for the items defined in `ADOPTERS.md`) are currently missing:
* `Deckhouse.png`;
* `Killercoda.png`;
* `osbuildoperator.png`;
* `Puzl.png` (there is `puzl.png`, though);
* `Trilio.png`.

**What you expected to happen**:
Due to this problem, an adopters list displayed at http://kubevirt.io/ is outdated.

All required images should be added to the repo or a workaround should be made allowing to generate `adopters.yml` for items having no images.

It is also important to mention the requirement of uploading images for people who edit the `ADOPTERS.md` file.

**Anything else we need to know?**:

**Comment by cwilkers** [comment]
Seems like an input handling bug in the script, since the ADOPTERS.md file in kubevirt/kubevirt is hand maintained. I'll investigate.

**Comment by cwilkers** [comment]
You're right, it's a missing image. I'll add some logic to the `logo` function to give more useful feedback when images are missing.

**Comment by cwilkers** [comment]
I believe we can close this due to #890
