### ISSUE TITLE
Deployment code block doesn't filter alpha releases

### ISSUE THREAD

**Issue by relaxdiego** [kubevirt/kubevirt.github.io#891]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When deploying KubeVirt using the code block provided in the quick start guides, alpha releases aren't filtered.

**What you expected to happen**:

When deploying using the sample code blocks, only stable releases are deployed.

**Anything else we need to know?**:

Sample code block that doesn't filter alpha releases:

```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
```

Suggested alternate code block to filter alpha releases, assuming all tag_names are SemVer compliant:

```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-.*$' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
```

Affected guides:

1. https://kubevirt.io/quickstart_kind/
2. https://kubevirt.io/quickstart_cloud/

**Comment by cwilkers** [comment]
By the time I come to test some code, v0.59.0 is released, so no more rcs at the top of the list. When an alpha release/candidate was at the top, was it also latest? As in, if you add "/latest" to the end of the URL in the curl, was it still pointing to an RC?
If so, I think I have an all awk way to handle this. (I'm writing install instructions in a different guide.)

```
curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | awk -F '[ \t":]+' '$2 =="tag_name" && $3 ~ /^[^-]+$/ {print $3;exit 0}'
```

I mean, if we're going to be using awk anyway, let's really use awk :-)

**Comment by JM1** [comment]
@cwilkers atm the latest release is `v0.60.0-alpha.0`. Regarding your `/latest` question:

```console
$ curl -s https://api.github.com/repos/kubevirt/kubevirt/releases/latest | grep tag_name
  "tag_name": "v0.59.0",
```

```console
$ curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name
    "tag_name": "v0.60.0-alpha.0",
    "tag_name": "v0.59.0",
    "tag_name": "v0.59.0-rc.2",
    ...
```

**Comment by cwilkers** [comment]
More recently (and actually that means going back four months), I have been seeing blogs using a much simpler artifact to get the most recent stable release:

`curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt`

and to consume it:

```bash
export RELEASE=$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)
```

All in favor? With this much simpler version PRs to add this in should be greatly simplified.
