### ISSUE TITLE
Getting Started material does not work on Minikube 1.10 or Minishift 3.10 with KubeVirt >= 0.7.0

### ISSUE THREAD

**Issue by xsgordon** [kubevirt/kubevirt.github.io#95]
Due to https://github.com/kubevirt/kubevirt/issues/1316 it appears that KubeVirt 0.7.0 and higher . Instead for recent demos I have had to peg the version to 0.6.4. Until this is fixed the documentation should refer to a combination that is known to work.

Following the fix to minikube/minishift arriving we would still need a note to indicate that a "known bad" combination exists with the resolution being to use a higher minishift version.

/cc @karmab @fabiand @simon3z

**Comment by simon3z** [comment]
> Until this is fixed the documentation should refer to a combination that is known to work.

+1 :+1:

> Following the fix to minikube/minishift arriving we would still need a note to indicate that a "known bad" combination exists with the resolution being to use a higher minishift version.

In the past discussing with @scollier we were planning validations to run at the beginning so we would catch these even if someone missed the notes. After all that's what minishift deos as well:

```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... FAIL
-- Checking if requested OpenShift version 'v3.10.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
```

**Comment by xsgordon** [comment]
Workarounds required for minishift (I mount this script in using a hostmount):

https://github.com/xsgordon/kubevirt-minishift-demo/blob/master/workarounds.sh
